# PyTorch 基础 : 张量
在第一章中我们已经通过官方的入门教程对PyTorch有了一定的了解，这一章会详细介绍PyTorch 里面的基础知识。
全部掌握了这些基础知识，在后面的应用中才能更加快速进阶，如果你已经对PyTorch有一定的了解，可以跳过此章

In [2]:
# 首先要引入相关的包
import torch
# 在使用NumPy库之前，首先必须导入该函数库，导入方式如下：import numpy as np
import numpy as np
#打印一下版本
torch.__version__

'1.7.1'

## 张量(Tensor)
张量的英文是Tensor，它是PyTorch里面基础的运算单位，与Numpy的ndarray相同都表示的是一个多维的矩阵。
与ndarray的最大区别就是，PyTorch的Tensor可以在 GPU 上运行，而 numpy 的 ndarray 只能在 CPU 上运行，在GPU上运行大大加快了运算速度。

下面我们生成一个简单的张量

In [3]:
x = torch.rand(2, 3)
x

tensor([[0.0549, 0.8896, 0.0511],
        [0.4283, 0.2281, 0.8814]])

以上生成了一个，2行3列的的矩阵，我们看一下他的大小：

In [4]:
# 可以使用与numpy相同的shape属性查看
print(x.shape)
# 也可以使用size()函数，返回的结果都是相同的
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


张量（Tensor）是一个定义在一些向量空间和一些对偶空间的笛卡儿积上的多重线性映射，其坐标是|n|维空间内，有|n|个分量的一种量， 其中每个分量都是坐标的函数， 而在坐标变换时，这些分量也依照某些规则作线性变换。r称为该张量的秩或阶（与矩阵的秩和阶均无关系）。 (来自百度百科)

下面我们来生成一些多维的张量：

In [5]:
# torch.rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
# torch.rand(tensor的shape, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
y=torch.rand(2,3,4,5)
print(y.size())
y

torch.Size([2, 3, 4, 5])


tensor([[[[0.1964, 0.8360, 0.3870, 0.2324, 0.9221],
          [0.2724, 0.4472, 0.8439, 0.8584, 0.6800],
          [0.6733, 0.2254, 0.0343, 0.0524, 0.5873],
          [0.0627, 0.9765, 0.4664, 0.6183, 0.2255]],

         [[0.9904, 0.4661, 0.8847, 0.3374, 0.1895],
          [0.6626, 0.9384, 0.4187, 0.1513, 0.8640],
          [0.0570, 0.2389, 0.4787, 0.5615, 0.6750],
          [0.2181, 0.8945, 0.8001, 0.6001, 0.7256]],

         [[0.1366, 0.1484, 0.3879, 0.7956, 0.8027],
          [0.2005, 0.5247, 0.8165, 0.8848, 0.0247],
          [0.0139, 0.8243, 0.6526, 0.3576, 0.3130],
          [0.0458, 0.5532, 0.4798, 0.1736, 0.1280]]],


        [[[0.7432, 0.8580, 0.3981, 0.8539, 0.6805],
          [0.2930, 0.9598, 0.8006, 0.5271, 0.3944],
          [0.2317, 0.0794, 0.1270, 0.2592, 0.2690],
          [0.5541, 0.0296, 0.1400, 0.3943, 0.0175]],

         [[0.3168, 0.7702, 0.1161, 0.1255, 0.3946],
          [0.0813, 0.1603, 0.3817, 0.1038, 0.4530],
          [0.8940, 0.2474, 0.0093, 0.5182, 0.5453],
  

在同构的意义下，第零阶张量 （r = 0） 为标量 （Scalar），第一阶张量 （r = 1） 为向量 （Vector）， 第二阶张量 （r = 2） 则成为矩阵 （Matrix），第三阶以上的统称为多维张量。

其中要特别注意的就是标量，我们先生成一个标量：


In [6]:
#我们直接使用现有数字生成
scalar =torch.tensor(3.1433223)
print(scalar)
#打印标量的大小
scalar.size()

tensor(3.1433)


torch.Size([])

对于标量，我们可以直接使用 .item() 从中取出其对应的python对象的数值

In [7]:
scalar.item()

3.143322229385376

特别的：如果张量中只有一个元素的tensor也可以调用`tensor.item`方法

In [8]:
tensor = torch.tensor([3.1433223]) 
print(tensor)
tensor.size()

tensor([3.1433])


torch.Size([1])

In [9]:
tensor.item()

3.143322229385376

### 基本类型
Tensor的基本数据类型有五种：
- 32位浮点型：torch.FloatTensor。 (默认)
- 64位整型：torch.LongTensor。
- 32位整型：torch.IntTensor。
- 16位整型：torch.ShortTensor。
- 64位浮点型：torch.DoubleTensor。

除以上数字类型外，还有
byte和chart型

#### 以下为各函数的默认值

In [10]:
long=tensor.long()
long

tensor([3])

In [35]:
half=tensor.half()
half

tensor([3.1426], dtype=torch.float16)

In [12]:
int_t=tensor.int()
int_t

tensor([3], dtype=torch.int32)

In [13]:
flo = tensor.float()
flo

tensor([3.1433])

In [14]:
short = tensor.short()
short

tensor([3], dtype=torch.int16)

In [15]:
ch = tensor.char()
ch

tensor([3], dtype=torch.int8)

In [16]:
bt = tensor.byte()
bt

tensor([3], dtype=torch.uint8)

### Numpy转换
使用numpy方法将Tensor转为ndarray

NumPy（Numerical Python）是Python的一种开源的数值计算扩展。这种工具可用来存储和处理大型矩阵，比Python自身的嵌套列表（nested list structure)结构要高效的多（该结构也可以用来表示矩阵（matrix）），支持大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库

这是因为ndarray中的所有元素的类型都是相同的，而Python列表中的元素类型是任意的，所以ndarray在存储元素时内存可以连续，而python原生list就只能通过寻址方式找到下一个元素，这虽然也导致了在通用性能方面Numpy的ndarray不及Python原生list，但在科学计算中，Numpy的ndarray就可以省掉很多循环语句，代码使用方面比Python原生list简单的多。

#### numpy内置了并行运算功能，当系统有多个核心时，做某种计算时，numpy会自动做并行计算。
#### Numpy底层使用C语言编写，数组中直接存储对象，而不是存储对象指针，所以其运算效率远高于纯Python代码。

In [17]:
a = torch.randn((3, 2))
# tensor转化为numpy
numpy_a = a.numpy()
print(numpy_a)

[[ 0.11013541 -1.0482366 ]
 [-0.5922969  -0.4621335 ]
 [-0.69766843 -0.1878442 ]]


numpy转化为Tensor


In [18]:
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[ 0.1101, -1.0482],
        [-0.5923, -0.4621],
        [-0.6977, -0.1878]])

***Tensor和numpy对象共享内存，所以他们之间的转换很快，而且几乎不会消耗什么资源。但这也意味着，如果其中一个变了，另外一个也会随之改变。***

### 设备间转换
一般情况下可以使用.cuda方法将tensor移动到gpu，这步操作需要cuda设备支持

In [19]:
cpu_a=torch.rand(4, 3)
cpu_a.type()

'torch.FloatTensor'

In [20]:
gpu_a=cpu_a.cuda()
gpu_a.type()

'torch.cuda.FloatTensor'

使用.cpu方法将tensor移动到cpu

In [21]:
cpu_b=gpu_a.cpu()
cpu_b.type()

'torch.FloatTensor'

如果我们有多GPU的情况，可以使用to方法来确定使用那个设备，这里只做个简单的实例：

In [22]:
#使用torch.cuda.is_available()来确定是否有cuda设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
#将tensor传送到设备
gpu_b=cpu_b.to(device)
gpu_b.type()

cuda


'torch.cuda.FloatTensor'

### 初始化
Pytorch中有许多默认的初始化方法可以使用

In [23]:
# 使用[0,1]均匀分布随机初始化二维数组
rnd = torch.rand(5, 3)
rnd

tensor([[0.6508, 0.4746, 0.3572],
        [0.4246, 0.6530, 0.7462],
        [0.4162, 0.6071, 0.7921],
        [0.7631, 0.1871, 0.3741],
        [0.8601, 0.5361, 0.7882]])

In [24]:
##初始化，使用1填充
one = torch.ones(2, 2)
one

tensor([[1., 1.],
        [1., 1.]])

In [25]:
##初始化，使用0填充
zero=torch.zeros(2,2)
zero

tensor([[0., 0.],
        [0., 0.]])

In [26]:
#初始化一个单位矩阵，即对角线为1 其他为0
eye=torch.eye(2,2)
eye

tensor([[1., 0.],
        [0., 1.]])

### 常用方法
PyTorch中对张量的操作api 和 NumPy 非常相似，如果熟悉 NumPy 中的操作，那么他们二者基本是一致的：

In [39]:
x = torch.randn(3, 3)
print(x)

tensor([[ 0.2787, -1.0876, -2.0723],
        [ 1.3065, -1.5274, -0.3547],
        [ 0.1867,  1.3164,  0.7708]])


In [40]:
# 沿着行取最大值
max_value, max_idx = torch.max(x, dim=1)
print(max_value, max_idx)

tensor([0.2787, 1.3065, 1.3164]) tensor([0, 0, 1])


In [41]:
# 每行 x 求和
print((0.2787)+ (-1.0876)+ (-2.0723))##还就真TM是看图说话呗
sum_x = torch.sum(x, dim=1)
print(sum_x)

-2.8811999999999998
tensor([-2.8812, -0.5756,  2.2738])


In [30]:
y=torch.randn(3, 3)
z = x + y
print(z)

tensor([[-1.8193e+00, -4.0827e-01, -4.7135e-04],
        [ 3.5275e-01,  8.4866e-01,  1.1249e-01],
        [-1.6040e+00,  1.6805e+00, -1.2439e+00]])


正如官方60分钟教程中所说，以_为结尾的，均会改变调用值

In [ ]:
# add 完成后x的值改变了
x.add_(y)## x = x + y
print(x)

张量的基本操作都介绍的的差不多了，下一章介绍PyTorch的自动求导机制